// Nội dung chi tiết của trang hướng dẫn (VI, EN): các bước phân tích và phần Giáo sư phản biện, kèm tên ảnh minh họa trong public/guide/<ngôn ngữ>/.
// Ảnh chụp từ chính ứng dụng (dữ liệu minh họa), có khung màu đánh dấu chỗ cần bấm. Mỗi bước: [tiêu đề, mô tả ngắn (dùng cho dữ liệu có cấu trúc), ý chi tiết, ảnh, chú thích ảnh].
export const CONTENT = {
  vi: {
    title: "Hướng dẫn dùng Ami - Trợ lý học thuật từng bước",
    desc: "Hướng dẫn từng bước dùng Ami - Trợ lý học thuật: nhập abstract, tải tài liệu, xem điểm 0–100, trích dẫn APA, và Giáo sư phản biện giả lập hội đồng.",
    h1: "Hướng dẫn sử dụng Ami",
    lead: "Ami là trợ lý học thuật AI của hệ sinh thái ISA: đọc tài liệu giúp bạn, chấm mức độ phù hợp với đề tài, gợi ý đoạn nên trích và tạo trích dẫn chuẩn. Trang này đi qua từng bước, có ảnh chụp từ ứng dụng; chỗ cần bấm được đánh dấu bằng khung màu.",
    toc: [["#phan-tich", "Phân tích tài liệu (8 bước)"], ["#giao-su", "Giáo sư phản biện"], ["#hoi-dap", "Câu hỏi thường gặp"]],
    glanceH: "Ami làm gì cho bạn",
    glance: [["Đọc và chấm điểm", "Nhận điểm 0–100 cho mức độ phù hợp của tài liệu với đề tài của bạn."], ["Trích dẫn đúng chuẩn", "Chọn đoạn đáng trích, sao chép trích dẫn APA, Harvard, IEEE và hơn 10.000 kiểu khác."], ["Giáo sư phản biện", "Tính năng cao cấp: giả lập hội đồng, nhận xét và đề xuất điểm cho đề cương, luận văn, luận án."]],
    stepsH: "Phân tích tài liệu: 8 bước",
    stepsLead: "Từ một tài liệu đến trích dẫn đúng chuẩn. Làm theo thứ tự; bạn có thể quay lại bước trước bất cứ lúc nào.",
    steps: [
      ["Đăng ký tài khoản", "Tạo tài khoản bằng email và xác nhận qua thư. Tài khoản Cơ bản có 1 lượt phân tích miễn phí mỗi tuần.",
        ["Mở Ami, bấm \"Chưa có tài khoản? Đăng ký\", nhập họ tên, email và mật khẩu từ 8 ký tự, đồng ý với điều khoản.", "Ami gửi thư xác nhận; bấm liên kết trong thư (xem cả thư rác nếu chưa thấy) rồi đăng nhập.", "Tài khoản Cơ bản dùng được ngay. Muốn hạn mức riêng, xem lịch sử đầy đủ và tải tệp lớn hơn, hãy xin xác thực tài khoản ở trang Hồ sơ."], "01-landing", "Biểu mẫu đăng ký của Ami"],
      ["Dán tóm tắt đề tài", "Nhập Abstract hoặc đề cương nghiên cứu. Đây là thước đo để Ami chấm mọi tài liệu.",
        ["Dán abstract hoặc đề cương của bạn, tối thiểu 40 từ. Càng nêu rõ mục tiêu, câu hỏi, khung lý thuyết và phương pháp thì điểm chấm càng sát.", "Có thể đặt tên đề tài để gom lịch sử trích dẫn theo đề tài. Abstract chỉ được lưu khi bạn bấm \"Lưu thành đề tài\"."], "02-abstract", "Bước 1: dán abstract rồi bấm Tiếp tục"],
      ["Tải tài liệu lên", "Chọn tệp PDF, DOC hoặc DOCX cần đánh giá. Tệp được đọc ngay trên máy bạn.",
        ["Kéo thả hoặc bấm để chọn tệp. Tối đa 2 MB với tài khoản chưa xác thực, 15 MB với tài khoản đã xác thực.", "Tệp được đọc ngay trên máy bạn; chỉ phần văn bản được gửi đi phân tích và không được lưu lại.", "Nếu là PDF scan (ảnh), Ami đề nghị nhận dạng chữ (OCR) ngay trên trình duyệt, tối đa 60 trang."], "03-upload", "Bước 2: tải tài liệu rồi bấm Phân tích"],
      ["Xem điểm phù hợp", "Nhận điểm từ 0 đến 100 theo năm tiêu chí, kèm tóm tắt, điểm mạnh và khoảng trống.",
        ["Điểm gồm năm tiêu chí: chủ đề (40), khái niệm và lý thuyết (20), phương pháp (15), bằng chứng (15) và tính cập nhật (10).", "Từ 60 điểm trở lên, tài liệu đạt ngưỡng trích dẫn. Phía dưới là tóm tắt, điểm mạnh và những chỗ tài liệu chưa phù hợp với đề tài."], "04-score", "Điểm phù hợp và năm tiêu chí"],
      ["Chọn đoạn đáng trích", "Từ 60 điểm trở lên, Ami gợi ý các đoạn nên trích, xếp theo mức ưu tiên, có số trang và được đối chiếu nguyên văn.",
        ["Mỗi đoạn có mức ưu tiên, loại (định nghĩa, kết quả, phương pháp…), số trang và lý do nên trích.", "Mọi đoạn đều được máy đối chiếu nguyên văn với tài liệu gốc; đoạn nào không khớp bị loại và Ami cho biết số đoạn bị loại.", "Tích chọn các đoạn bạn muốn dùng rồi bấm \"Trích dẫn các đoạn đã chọn\". Bạn vẫn nên đọc tài liệu gốc trước khi dựa vào."], "05-passages", "Danh sách đoạn nên trích, lọc theo mức ưu tiên"],
      ["Sao chép trích dẫn", "Chọn kiểu trích dẫn (APA, Harvard, IEEE…) rồi sao chép danh mục tham khảo và trích dẫn trong bài.",
        ["Chọn kiểu: APA 7, Harvard, Chicago, MLA, IEEE, Vancouver, AMA, BibTeX, RIS hoặc hơn 10.000 kiểu tạp chí và trường (CSL), bằng tiếng Việt hoặc tiếng Anh.", "Bấm Sao chép; khi dán vào Word, chữ in nghiêng được giữ nguyên.", "Có thể sửa thông tin nguồn (tác giả, năm, tạp chí) trước khi sao chép nếu Ami đọc chưa đúng."], "06-cite", "Trích dẫn trong bài và danh mục tài liệu tham khảo"],
      ["Xem lịch sử theo đề tài", "Các trích dẫn đã sao chép được gom theo đề tài; đổi kiểu và ngôn ngữ ngay tại từng nguồn.",
        ["Mục \"Lịch sử trích dẫn\" gom mọi trích dẫn bạn đã sao chép theo đề tài, kèm điểm phù hợp của từng nguồn.", "Tài khoản Cơ bản vẫn được lưu lịch sử nhưng chỉ xem lại đầy đủ khi đã xác thực."], "07-history", "Lịch sử trích dẫn gom theo đề tài"],
      ["Điểm thấp thì chọn hướng đi", "Dưới 60 điểm, Ami gợi ý tìm nguồn khác, chỉnh abstract và tạp chí phù hợp từ EduFind; bạn là người quyết định.",
        ["Dưới 60 điểm, Ami không đề xuất đoạn trích. Thay vào đó là các hướng đi: tìm nguồn khác, chỉnh lại abstract hoặc vẫn trích dẫn cả nguồn.", "Công trình và tạp chí gợi ý chi tiết dành cho tài khoản đã xác thực; tài khoản Cơ bản thấy số lượng gợi ý."], "08b-decision", "Các lựa chọn khi điểm dưới ngưỡng"],
    ],
    proH: "Giáo sư phản biện",
    proSub: "Giả lập hội đồng: đánh giá đề cương, luận văn, luận án",
    proBadge: "Tính năng cao cấp",
    proLead: "Giáo sư phản biện đóng vai người phản biện khắt khe nhưng công tâm. Bạn tải công trình và mẫu nhận xét của trường hoặc viện, Ami soạn bản nháp nhận xét từng mục, đề xuất điểm thang 100, khuyến nghị thông qua hoặc chỉnh sửa, câu hỏi dành cho tác giả; mọi trích dẫn minh chứng được máy đối chiếu với bản gốc.",
    proWho: ["Dành cho nhà khoa học đã xác thực và được quản trị viên phê duyệt. Mỗi lượt đọc toàn văn công trình nên tốn nhiều tài nguyên hơn một lần phân tích thường.", "Đây là bản nháp hỗ trợ: Ami không thay thế hội đồng thật, không kiểm tra đạo văn và không xác minh tài liệu tham khảo có thật. Người phản biện thẩm định, chỉnh sửa và chịu trách nhiệm về nội dung cuối cùng."],
    proStepsH: "Từ đề nghị đến bản nhận xét",
    proSteps: [
      ["Tìm mục Giáo sư phản biện", "Mục có biểu tượng ngôi sao ở thanh menu; trang Phân tích cũng có biểu ngữ giới thiệu.", "p0-menu", "Mục Giáo sư phản biện trên thanh menu"],
      ["Xác thực tài khoản", "Tài khoản chưa xác thực chỉ thấy giới thiệu. Liên hệ tác giả để xác thực (họ tên, đơn vị, ORCID).", "p1-locked", "Tài khoản chưa xác thực"],
      ["Gửi đề nghị kèm lý do và minh chứng", "Tài khoản đã xác thực gửi đề nghị cấp hạn mức: nêu lý do cần dùng và minh chứng khoa học cụ thể (ORCID, công bố, đề tài, vai trò phản biện).", "p2-request", "Biểu mẫu đề nghị: lý do tối thiểu 40 ký tự, minh chứng tối thiểu 20 ký tự"],
      ["Chờ quản trị viên duyệt", "Mỗi người có một đề nghị chờ duyệt. Khi được duyệt, mục này mở ngay; nếu chưa được, bạn bổ sung minh chứng và gửi lại.", "p3-pending", "Đề nghị đang chờ duyệt"],
      ["Chọn loại văn bản, vai trò và khung mẫu", "Chọn đề cương, bài báo, luận văn hoặc luận án; chọn vai trò; dùng mẫu có sẵn hoặc tải mẫu nhận xét của trường/viện để Ami làm theo từng mục.", "p4-setup", "Thiết lập loại văn bản, vai trò và khung mẫu"],
      ["Tải công trình cần phản biện", "Chọn tệp DOCX hoặc PDF có chữ. Tệp được đọc ngay trên máy bạn; công trình quá dài (hơn khoảng 900 nghìn ký tự) nên tách theo chương.", "p5-upload", "Chọn công trình rồi bấm Soạn bản nháp phản biện"],
      ["Giáo sư soạn bản nháp", "Ami đọc toàn văn, nhận xét theo từng lô mục rồi tổng hợp điểm. Có thể mất vài phút; hãy giữ trang mở cho tới khi xong.", "p6-running", "Tiến trình soạn nhận xét"],
      ["Đọc điểm và khuyến nghị", "Điểm đề xuất do máy cộng từ điểm thành phần; khuyến nghị theo ngưỡng điểm và có thể bị hạ nếu có khuyết điểm rất nghiêm trọng.", "p7-result", "Điểm đề xuất, khuyến nghị và nút tải bản nháp"],
      ["Xem nhận xét và bằng chứng", "Mỗi mục có nhận xét, ưu điểm, hạn chế, yêu cầu chỉnh sửa theo mức ưu tiên và các đoạn trích nguyên văn đã được đối chiếu với bản gốc.", "p8-sections", "Một mục nhận xét kèm trích dẫn bằng chứng"],
    ],
    proAfter: ["Tải bản nháp về Word (.docx) để chỉnh sửa và hoàn thiện. Kết quả chỉ lưu trên trình duyệt của bạn (tối đa 5 bản gần nhất) và xóa được bất cứ lúc nào.", "Nếu lỗi trước khi có kết quả nào, lượt dùng được hoàn lại."],
    proScaleH: "Cách đọc điểm và khuyến nghị",
    proScale: [["Dưới 40", "Từ chối, nên viết lại toàn bộ"], ["40–54", "Chỉnh sửa lớn và phản biện lại"], ["55–59", "Chỉnh sửa trước khi thông qua"], ["60–74", "Thông qua có điều kiện"], ["Từ 75", "Thông qua, chỉnh sửa nhỏ"]],
    proScaleNote: "Có khuyết điểm rất nghiêm trọng thì khuyến nghị không được tốt hơn \"chỉnh sửa lớn\", dù điểm cao.",
    proAdminH: "Dành cho quản trị viên",
    proAdmin: "Ở Quản trị, tab Giáo sư phản biện liệt kê đề nghị kèm lý do và minh chứng. Quản trị viên phê duyệt kèm số lượt mỗi tuần, từ chối kèm ghi chú, hoặc thu hồi sau này.",
    proAdminImg: ["p9-admin", "Duyệt đề nghị: lý do, minh chứng, số lượt mỗi tuần"],
    figure: "Hình",
  },
  en: {
    title: "Ami AI Academic Agent guide: step by step",
    desc: "Step-by-step guide to Ami, the AI Academic Agent: paste your abstract, upload a source, read the 0–100 fit score, cite in APA, and use the AI Professor review.",
    h1: "How to use Ami",
    lead: "Ami is the AI academic assistant of the ISA ecosystem: it reads sources for you, scores their fit to your study, suggests the passages worth citing and creates correct citations. This page walks through every step with screenshots from the app; what to click is marked with a coloured frame.",
    toc: [["#phan-tich", "Analyse a source (8 steps)"], ["#giao-su", "AI Professor review"], ["#hoi-dap", "FAQ"]],
    glanceH: "What Ami does for you",
    glance: [["Read and score", "Get a 0–100 score for how well a source fits your study."], ["Cite correctly", "Pick citable passages and copy citations in APA, Harvard, IEEE and 10,000+ other styles."], ["AI Professor", "A premium feature: a simulated committee that reviews and scores proposals, theses and dissertations."]],
    stepsH: "Analyse a source: 8 steps",
    stepsLead: "From a source document to a correct citation. Follow the order; you can go back to an earlier step at any time.",
    steps: [
      ["Create an account", "Create an account with your email and confirm by mail. A Basic account gets 1 free analysis per week.",
        ["Open Ami, press \"No account? Sign up\", enter your name, email and a password of 8+ characters, and accept the terms.", "Ami sends a confirmation email; press the link (check spam if you cannot see it) and sign in.", "A Basic account works right away. For a personal allowance, full history and larger files, ask to have your account verified on the Profile page."], "01-landing", "The Ami sign-up form"],
      ["Paste your abstract", "Enter your abstract or research proposal. This is the yardstick Ami uses to score every source.",
        ["Paste your abstract or proposal, at least 40 words. The clearer the aims, questions, framework and method, the closer the score.", "You can name the topic to group your citation history. The abstract is saved only when you press \"Save as topic\"."], "02-abstract", "Step 1: paste your abstract, then press Continue"],
      ["Upload a source", "Choose the PDF, DOC or DOCX file to assess. The file is read on your device.",
        ["Drag and drop or click to choose a file. Up to 2 MB for unverified accounts, 15 MB for verified ones.", "The file is read on your device; only the text is sent for analysis and it is not stored.", "For a scanned PDF (images), Ami offers in-browser text recognition (OCR), up to 60 pages."], "03-upload", "Step 2: upload the source, then press Analyse"],
      ["Read the fit score", "Get a score from 0 to 100 over five criteria, with a summary, strengths and gaps.",
        ["The score has five criteria: topic (40), concepts and theory (20), method (15), evidence (15) and currency (10).", "From 60 points a source passes the citation threshold. Below it you get a summary, strengths and where the source does not fit your study."], "04-score", "The fit score and its five criteria"],
      ["Pick citable passages", "From 60 points Ami suggests passages to cite, ranked by priority, with page numbers, checked verbatim.",
        ["Each passage shows its priority, type (definition, finding, method…), page number and why it is worth citing.", "Every passage is checked verbatim against the source by machine; any that does not match is dropped and Ami tells you how many were dropped.", "Tick the passages you want and press \"Cite selected passages\". You should still read the source before relying on it."], "05-passages", "Suggested passages, filtered by priority"],
      ["Copy the citation", "Pick a citation style (APA, Harvard, IEEE…) and copy the reference list entry and the in-text citation.",
        ["Choose APA 7, Harvard, Chicago, MLA, IEEE, Vancouver, AMA, BibTeX, RIS or 10,000+ journal and university styles (CSL), in Vietnamese or English.", "Press Copy; italics are kept when you paste into Word.", "You can edit the source details (authors, year, journal) before copying if Ami read them wrongly."], "06-cite", "In-text citation and reference list entry"],
      ["Review your history by topic", "Copied citations are grouped by topic; change style and language right at each source.",
        ["\"Citation history\" groups every citation you copied by topic, with each source's fit score.", "Basic accounts still have their history saved but can review it in full only once verified."], "07-history", "Citation history grouped by topic"],
      ["Choose a path when the score is low", "Below 60, Ami points to other sources, abstract edits and suitable journals from EduFind; you decide.",
        ["Below 60, Ami suggests no passages. Instead you get paths: find other sources, edit your abstract, or cite the source anyway.", "Detailed suggested works and journals are for verified accounts; Basic accounts see the number of suggestions."], "08b-decision", "Your options when the score is below the threshold"],
    ],
    proH: "AI Professor review",
    proSub: "A simulated committee: review proposals, theses and dissertations",
    proBadge: "Premium feature",
    proLead: "The AI Professor plays a demanding but fair reviewer. You upload a work and your institution's review template; Ami drafts section-by-section comments, a proposed score out of 100, an accept or revise recommendation and questions for the author; every evidence quote is checked by machine against the original.",
    proWho: ["For verified researchers approved by the administrator. Each review reads the full work, so it uses far more resources than a normal analysis.", "This is a drafting aid: Ami does not replace a real committee, does not check plagiarism and does not verify that references exist. The reviewer verifies, edits and stays responsible for the final text."],
    proStepsH: "From request to review",
    proSteps: [
      ["Find the AI Professor", "It has a star icon in the menu; the Analyse page also shows an introduction banner.", "p0-menu", "The AI Professor item in the menu"],
      ["Get your account verified", "Unverified accounts only see the introduction. Contact the author to get verified (name, affiliation, ORCID).", "p1-locked", "An unverified account"],
      ["Send a request with reason and evidence", "A verified account sends a request for a quota: say why you need it and give concrete scientific evidence (ORCID, publications, projects, reviewing roles).", "p2-request", "The request form: reason at least 40 characters, evidence at least 20"],
      ["Wait for approval", "Each person has one pending request. Once approved, the page opens right away; if not, add evidence and send it again.", "p3-pending", "A request awaiting review"],
      ["Choose document type, role and template", "Pick proposal, article, thesis or dissertation; pick your role; use a built-in template or upload your institution's review template so Ami follows it section by section.", "p4-setup", "Setting up document type, role and template"],
      ["Upload the work to review", "Choose a DOCX or text PDF. The file is read on your device; a very long work (over about 900 thousand characters) should be split by chapter.", "p5-upload", "Choose the work, then press Draft the review"],
      ["The Professor drafts the review", "Ami reads the whole text, comments in batches of sections and then compiles the score. It can take a few minutes; keep the page open until it finishes.", "p6-running", "Drafting progress"],
      ["Read the score and recommendation", "The proposed score is summed by code from the component scores; the recommendation follows the score thresholds and can be lowered by a fatal defect.", "p7-result", "Proposed score, recommendation and the download button"],
      ["Read comments and evidence", "Each section has comments, strengths, weaknesses, requested revisions by priority and verbatim quotes checked against the original.", "p8-sections", "A section comment with evidence quotes"],
    ],
    proAfter: ["Download the draft as Word (.docx) to edit and finish. Results are kept only in your browser (latest 5) and can be deleted at any time.", "If it fails before any result, the credit is refunded."],
    proScaleH: "How to read the score and recommendation",
    proScale: [["Below 40", "Reject, rewrite entirely"], ["40–54", "Major revision and re-review"], ["55–59", "Revise before approval"], ["60–74", "Accept with conditions"], ["75 and above", "Accept, minor changes"]],
    proScaleNote: "With a fatal defect the recommendation cannot be better than \"major revision\", however high the score.",
    proAdminH: "For administrators",
    proAdmin: "Under Admin, the AI Professor tab lists requests with reasons and evidence. The administrator approves with a weekly quota, rejects with a note, or revokes later.",
    proAdminImg: ["p9-admin", "Reviewing a request: reason, evidence, weekly quota"],
    figure: "Figure",
  },
};
