// Từ điển song ngữ Việt/Anh. Thêm khóa mới ở đây; kiểu `Key` tự cập nhật.
const D = {
  // ----- Chung -----
  theme: { vi: "Đổi giao diện sáng/tối", en: "Toggle light/dark theme" },
  nav_work: { vi: "Phân tích", en: "Analyse" },
  nav_history: { vi: "Lịch sử trích dẫn", en: "Citation history" },
  nav_profile: { vi: "Hồ sơ", en: "Profile" },
  nav_admin: { vi: "Quản trị", en: "Admin" },
  sign_out: { vi: "Đăng xuất", en: "Sign out" },
  back: { vi: "Quay lại", en: "Back" },
  next: { vi: "Tiếp tục", en: "Continue" },
  save: { vi: "Lưu", en: "Save" },
  saved: { vi: "Đã lưu.", en: "Saved." },
  edit: { vi: "Chỉnh sửa", en: "Edit" },
  hide: { vi: "Thu gọn", en: "Collapse" },
  delete: { vi: "Xóa", en: "Delete" },
  confirm_delete: { vi: "Xóa mục này khỏi lịch sử?", en: "Delete this entry from your history?" },
  forbidden: { vi: "Bạn không có quyền truy cập trang này.", en: "You do not have access to this page." },
  setup_title: { vi: "Cần cấu hình Supabase", en: "Supabase setup required" },
  setup_body: { vi: "Đặt hai biến môi trường sau (xem README), rồi chạy lại ứng dụng:", en: "Set these two environment variables (see README), then restart the app:" },

  // ----- Trang chào / đăng nhập -----
  hero_eyebrow: { vi: "Dành cho nhà nghiên cứu · Song ngữ Việt/Anh", en: "For researchers · Vietnamese/English" },
  hero_lead: {
    vi: "Tải một tài liệu, nhập abstract hoặc đề cương của bạn. Hệ thống đọc, chấm mức độ phù hợp trên thang 100, đánh dấu các đoạn đáng trích dẫn theo thứ tự ưu tiên và tạo trích dẫn đúng chuẩn quốc tế.",
    en: "Upload a document and paste your abstract or proposal. The system reads it, scores its fit out of 100, highlights the passages worth citing in priority order and produces citations in international styles.",
  },
  flow1: { vi: "Nhập Abstract/Proposal", en: "Enter your abstract" },
  flow1d: { vi: "Mô tả nghiên cứu của bạn", en: "Describe your own study" },
  flow2: { vi: "Tải tài liệu", en: "Upload a source" },
  flow2d: { vi: "PDF, DOC, DOCX dưới 10 MB", en: "PDF, DOC, DOCX under 10 MB" },
  flow3: { vi: "Xem đánh giá", en: "Review the fit" },
  flow3d: { vi: "Điểm, tóm tắt, đoạn nên trích", en: "Score, summary, passages to cite" },
  flow4: { vi: "Sao chép trích dẫn", en: "Copy the citation" },
  flow4d: { vi: "APA, Harvard, IEEE, Vancouver…", en: "APA, Harvard, IEEE, Vancouver…" },
  f1_t: { vi: "Chấm điểm phù hợp", en: "Fit scoring" },
  f1_d: { vi: "Thang 100 điểm theo năm tiêu chí: chủ đề, khái niệm, phương pháp, bằng chứng, tính cập nhật.", en: "A 100-point scale across five criteria: topic, concepts, method, evidence, currency." },
  f2_t: { vi: "Trích đoạn nguyên văn", en: "Verbatim passages" },
  f2_d: { vi: "Mọi đoạn đề xuất đều được đối chiếu với văn bản gốc, nên không có câu trích bịa.", en: "Every suggested passage is checked against the source text, so nothing is fabricated." },
  f3_t: { vi: "Chuẩn trích dẫn quốc tế", en: "International styles" },
  f3_d: { vi: "Chín định dạng, tiếng Việt hoặc tiếng Anh, sao chép giữ nguyên chữ nghiêng khi dán vào Word.", en: "Nine formats in Vietnamese or English; italics are preserved when pasting into Word." },
  f4_t: { vi: "Không lưu tài liệu", en: "Documents not stored" },
  f4_d: { vi: "Tệp được đọc ngay trên máy bạn; hệ thống chỉ lưu lịch sử trích dẫn đã sao chép.", en: "Files are read on your device; only the citations you copied are saved." },
  signin: { vi: "Đăng nhập", en: "Sign in" },
  signup: { vi: "Tạo tài khoản", en: "Create account" },
  reset: { vi: "Đặt lại mật khẩu", en: "Reset password" },
  send_reset: { vi: "Gửi liên kết đặt lại", en: "Send reset link" },
  reset_sent: { vi: "Đã gửi liên kết đặt lại mật khẩu. Hãy kiểm tra hộp thư.", en: "Reset link sent. Check your inbox." },
  check_email: { vi: "Kiểm tra email của bạn", en: "Check your email" },
  sent_body: { vi: "Chúng tôi đã gửi liên kết xác thực đến {email}. Bấm vào liên kết đó để kích hoạt tài khoản.", en: "We sent a verification link to {email}. Open it to activate your account." },
  sent_hint: { vi: "Không thấy thư? Hãy xem mục Spam/Quảng cáo, hoặc gửi lại.", en: "No email? Check Spam/Promotions, or resend." },
  resend: { vi: "Gửi lại email xác thực", en: "Resend verification email" },
  resent: { vi: "Đã gửi lại email xác thực.", en: "Verification email resent." },
  back_signin: { vi: "Quay lại đăng nhập", en: "Back to sign in" },
  full_name: { vi: "Họ và tên", en: "Full name" },
  password: { vi: "Mật khẩu", en: "Password" },
  pw_hint: { vi: "Tối thiểu 8 ký tự.", en: "At least 8 characters." },
  agree: { vi: "Tôi đồng ý chỉ dùng hệ thống cho mục đích học thuật và hiểu rằng bản quyền phần mềm thuộc về tác giả.", en: "I agree to use the system for academic purposes and understand the software is proprietary to its author." },
  have_account: { vi: "Đã có tài khoản? Đăng nhập", en: "Have an account? Sign in" },
  no_account: { vi: "Chưa có tài khoản? Đăng ký", en: "No account? Sign up" },
  forgot: { vi: "Quên mật khẩu?", en: "Forgot password?" },
  free_note: { vi: "Miễn phí 2 lượt phân tích mỗi ngày. Cần thêm lượt, vui lòng liên hệ quản trị viên.", en: "2 free analyses per day. For more, contact the administrator." },
  err_login: { vi: "Email hoặc mật khẩu không đúng.", en: "Incorrect email or password." },
  err_exists: { vi: "Email này đã được đăng ký. Hãy đăng nhập hoặc đặt lại mật khẩu.", en: "This email is already registered. Sign in or reset your password." },
  err_rate: { vi: "Thao tác quá nhanh. Vui lòng thử lại sau ít phút.", en: "Too many attempts. Please try again in a few minutes." },
  err_weak: { vi: "Mật khẩu chưa đủ mạnh (tối thiểu 8 ký tự).", en: "Password is too weak (minimum 8 characters)." },
  err_agree: { vi: "Vui lòng đồng ý với điều khoản sử dụng.", en: "Please accept the terms of use." },
  err_unverified: { vi: "Email chưa được xác thực. Hãy mở liên kết trong thư xác thực, hoặc gửi lại thư.", en: "Email not verified yet. Open the link in your verification email, or resend it." },

  // ----- Hạn mức -----
  quota_unlimited: { vi: "Tài khoản quản trị: không giới hạn lượt", en: "Admin account: unlimited analyses" },
  quota_free: { vi: "Còn {left}/{total} lượt miễn phí hôm nay", en: "{left}/{total} free analyses left today" },
  quota_bonus: { vi: "+{n} lượt cấp thêm", en: "+{n} granted" },
  quota_out_title: { vi: "Bạn đã dùng hết lượt hôm nay", en: "You have used today's analyses" },
  quota_out_body: { vi: "Hạn mức miễn phí đặt lại lúc 00:00 (giờ Việt Nam). Để dùng thêm ngay, hãy liên hệ quản trị viên để được cấp thêm lượt.", en: "The free allowance resets at 00:00 (Vietnam time). To continue now, contact the administrator to be granted more analyses." },
  contact_missing: { vi: "Quản trị viên chưa công bố thông tin liên hệ.", en: "The administrator has not published contact details yet." },
  contact_subject: { vi: "Đề nghị cấp thêm lượt sử dụng", en: "Request for additional analyses" },
  contact_body: { vi: "Kính gửi quản trị viên, tôi xin được cấp thêm lượt sử dụng.", en: "Dear administrator, I would like to request additional analyses." },
  will_use: { vi: "Mỗi lần phân tích tính một lượt. Nếu phân tích lỗi, lượt sẽ được hoàn lại.", en: "Each analysis uses one credit. If it fails, the credit is refunded." },
  usage_life: { vi: "Tổng số lần phân tích đã dùng: {n}", en: "Analyses used in total: {n}" },

  // ----- Phân tích -----
  work_title: { vi: "Phân tích tài liệu", en: "Analyse a document" },
  step1: { vi: "Abstract", en: "Abstract" },
  step2: { vi: "Tài liệu", en: "Document" },
  step3: { vi: "Đánh giá", en: "Review" },
  step4: { vi: "Trích dẫn", en: "Cite" },
  abstract_h: { vi: "Bước 1. Nghiên cứu của bạn", en: "Step 1. Your research" },
  abstract_d: { vi: "Dán abstract hoặc đề cương (proposal). Nội dung này là chuẩn để đo mức phù hợp của mọi tài liệu bạn tải lên.", en: "Paste your abstract or proposal. It is the yardstick for how well any uploaded document fits." },
  abstract_ph: { vi: "Mục tiêu, câu hỏi nghiên cứu, khung lý thuyết, phương pháp, bối cảnh…", en: "Aims, research questions, theoretical framework, method, context…" },
  project_label: { vi: "Tên đề tài (tùy chọn, để gắn vào lịch sử trích dẫn)", en: "Project name (optional, tagged on your citation history)" },
  project_ph: { vi: "Ví dụ: Luận án - Chương 2", en: "e.g. Thesis - Chapter 2" },
  word_count: { vi: "{n} từ (tối thiểu {min})", en: "{n} words (minimum {min})" },
  upload_h: { vi: "Bước 2. Tải tài liệu cần đánh giá", en: "Step 2. Upload the source to evaluate" },
  upload_d: { vi: "Chấp nhận PDF, DOC, DOCX dưới {mb} MB (có thể chứa hình ảnh). Chỉ đọc tài liệu tiếng Anh hoặc tiếng Việt.", en: "PDF, DOC and DOCX under {mb} MB (images allowed). Only English or Vietnamese documents are supported." },
  drop_here: { vi: "Kéo thả tệp vào đây hoặc bấm để chọn", en: "Drop a file here or click to choose" },
  reading: { vi: "Đang đọc tệp trên máy của bạn…", en: "Reading the file on your device…" },
  chars: { vi: "{n} ký tự văn bản", en: "{n} characters of text" },
  replace_file: { vi: "Bấm để chọn tệp khác", en: "Click to choose another file" },
  privacy_note: { vi: "Tệp được đọc ngay trên máy bạn; chỉ phần văn bản được gửi đi phân tích và không được lưu lại.", en: "The file is read on your device; only its text is sent for analysis and it is never stored." },
  analyze: { vi: "Phân tích", en: "Analyse" },
  busy_note: { vi: "Thường mất từ 20 đến 90 giây. Vui lòng không đóng trang.", en: "Usually 20 to 90 seconds. Please keep this page open." },
  phase0: { vi: "Đang đọc toàn bộ tài liệu…", en: "Reading the whole document…" },
  phase1: { vi: "Đang đối chiếu với nghiên cứu của bạn…", en: "Comparing with your research…" },
  phase2: { vi: "Đang chấm điểm và chọn đoạn đáng trích…", en: "Scoring and selecting passages…" },
  phase3: { vi: "Đang kiểm chứng trích đoạn với văn bản gốc…", en: "Verifying passages against the source…" },
  err_file_type: { vi: "Chỉ nhận tệp PDF, DOC hoặc DOCX hợp lệ.", en: "Only valid PDF, DOC or DOCX files are accepted." },
  err_file_size: { vi: "Tệp vượt quá {mb} MB.", en: "The file exceeds {mb} MB." },
  err_file_empty: { vi: "Tệp trống.", en: "The file is empty." },
  err_file_no_text: { vi: "Không tìm thấy văn bản trong tệp. Có thể đây là bản quét hình ảnh. Hãy dùng bản PDF có thể chọn chữ.", en: "No text found in the file. It may be a scanned image. Please use a PDF with selectable text." },
  err_file_ocr_too_long: { vi: "Bản quét có quá nhiều trang cần OCR (tối đa {n} trang). Hãy tách tệp thành các phần nhỏ hơn.", en: "This scan has too many pages to OCR (max {n}). Please split it into smaller parts." },
  err_file_ocr_failed: { vi: "Không khởi động được OCR (không tải được mô hình nhận dạng). Hãy kiểm tra kết nối mạng hoặc dùng bản PDF có lớp chữ.", en: "OCR could not start (the recognition models failed to load). Check your connection or use a PDF with a text layer." },
  err_file_cancelled: { vi: "Đã hủy.", en: "Cancelled." },
  cancel: { vi: "Hủy", en: "Cancel" },
  ocr_title: { vi: "Tệp có vẻ là bản quét ảnh", en: "This looks like a scanned document" },
  ocr_body: { vi: "Không có lớp chữ để đọc. Có thể nhận dạng chữ (OCR) ngay trên máy bạn: lần đầu tải mô hình ngôn ngữ khoảng 6 MB, mỗi trang mất vài giây, tối đa {n} trang. Tệp vẫn không rời khỏi máy.", en: "There is no text layer. You can run OCR right on your device: the first run downloads about 6 MB of language models, each page takes a few seconds, up to {n} pages. The file still never leaves your device." },
  ocr_run: { vi: "Chạy OCR (Việt + Anh)", en: "Run OCR (Vietnamese + English)" },
  ocr_model: { vi: "Đang tải mô hình nhận dạng chữ…", en: "Downloading the text-recognition models…" },
  ocr_running: { vi: "Đang nhận dạng chữ: trang {a}/{b}…", en: "Recognising text: page {a}/{b}…" },
  err_file_corrupt: { vi: "Không đọc được tệp (hỏng hoặc có mật khẩu).", en: "The file could not be read (corrupt or password-protected)." },
  err_unauthorized: { vi: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.", en: "Your session has expired. Please sign in again." },
  err_email_unverified: { vi: "Email chưa được xác thực.", en: "Email not verified." },
  err_suspended: { vi: "Tài khoản của bạn đang bị tạm khóa. Vui lòng liên hệ quản trị viên.", en: "Your account is suspended. Please contact the administrator." },
  err_quota_exhausted: { vi: "Bạn đã hết lượt sử dụng. Hãy liên hệ quản trị viên để được cấp thêm.", en: "You have no analyses left. Contact the administrator to be granted more." },
  err_unsupported_language: { vi: "Rất tiếc, hệ thống chỉ hỗ trợ tài liệu tiếng Anh hoặc tiếng Việt. Tài liệu này dùng ngôn ngữ khác nên không thể phân tích. Lượt dùng của bạn không bị trừ.", en: "Sorry, only English or Vietnamese documents are supported. This one appears to be in another language, so it cannot be analysed. No credit was used." },
  err_no_text: { vi: "Tài liệu không có đủ văn bản để phân tích.", en: "The document has too little text to analyse." },
  err_too_long: { vi: "Tài liệu quá dài để phân tích một lần. Hãy tách thành các chương hoặc phần.", en: "The document is too long to analyse in one go. Please split it into chapters or parts." },
  err_bad_request: { vi: "Yêu cầu không hợp lệ. Hãy kiểm tra abstract (đủ dài) và tệp.", en: "Invalid request. Check that your abstract is long enough and the file is valid." },
  err_ai_failed: { vi: "Dịch vụ AI gặp sự cố. Lượt dùng đã được hoàn lại, vui lòng thử lại.", en: "The AI service had a problem. Your credit was refunded; please try again." },
  err_ai_refused: { vi: "Dịch vụ AI từ chối xử lý tài liệu này. Lượt dùng đã được hoàn lại.", en: "The AI service declined to process this document. Your credit was refunded." },
  err_server_misconfigured: { vi: "Máy chủ chưa được cấu hình đầy đủ. Vui lòng báo quản trị viên.", en: "The server is not fully configured. Please tell the administrator." },
  err_network: { vi: "Không kết nối được máy chủ. Hãy kiểm tra mạng và thử lại.", en: "Could not reach the server. Check your connection and try again." },

  // ----- Kết quả -----
  score: { vi: "Điểm phù hợp", en: "Fit score" },
  pass: { vi: "Phù hợp để trích dẫn", en: "Suitable to cite" },
  fail: { vi: "Mức phù hợp thấp", en: "Low fit" },
  lang_vi: { vi: "Tiếng Việt", en: "Vietnamese" },
  lang_en: { vi: "Tiếng Anh", en: "English" },
  c_topic: { vi: "Chủ đề", en: "Topic" },
  c_concept: { vi: "Khái niệm, lý thuyết", en: "Concepts, theory" },
  c_method: { vi: "Phương pháp", en: "Method" },
  c_evidence: { vi: "Bằng chứng", en: "Evidence" },
  c_currency: { vi: "Tính cập nhật", en: "Currency" },
  summary: { vi: "Tóm tắt nội dung", en: "Summary" },
  strengths: { vi: "Điểm phù hợp", en: "Where it fits" },
  gaps: { vi: "Hạn chế so với nghiên cứu của bạn", en: "Gaps against your study" },
  passages_h: { vi: "Đoạn nên trích dẫn", en: "Passages to cite" },
  passages_d: { vi: "Xếp theo mức ưu tiên. Mọi đoạn là nguyên văn và đã được đối chiếu với tài liệu gốc. Chọn các đoạn bạn muốn dùng.", en: "Ranked by priority. Every passage is verbatim and verified against the source. Select the ones you want." },
  no_passages: { vi: "Không có đoạn nào vượt qua bước kiểm chứng nguyên văn.", en: "No passage passed the verbatim check." },
  dropped_note: { vi: "{n} đoạn do AI đề xuất đã bị loại vì không khớp nguyên văn với tài liệu.", en: "{n} AI-suggested passage(s) were dropped because they did not match the document verbatim." },
  selected_n: { vi: "Đã chọn {n}", en: "{n} selected" },
  cite_selected: { vi: "Trích dẫn các đoạn đã chọn", en: "Cite selected passages" },
  cite_whole: { vi: "Chỉ trích dẫn nguồn (không kèm đoạn)", en: "Cite the source only (no passage)" },
  cite_anyway: { vi: "Vẫn muốn trích dẫn nguồn này", en: "Cite this source anyway" },
  another_doc: { vi: "Phân tích tài liệu khác", en: "Analyse another document" },
  new_project: { vi: "Đề tài mới", en: "New project" },
  all: { vi: "Tất cả", en: "All" },
  priority: { vi: "Mức ưu tiên", en: "Priority" },
  prio_high: { vi: "Ưu tiên cao", en: "High" },
  prio_medium: { vi: "Trung bình", en: "Medium" },
  prio_low: { vi: "Thấp", en: "Low" },
  use_definition: { vi: "Định nghĩa", en: "Definition" },
  use_evidence: { vi: "Bằng chứng", en: "Evidence" },
  use_method: { vi: "Phương pháp", en: "Method" },
  use_finding: { vi: "Kết quả", en: "Finding" },
  use_theory: { vi: "Lý thuyết", en: "Theory" },
  use_context: { vi: "Bối cảnh", en: "Context" },
  page: { vi: "Trang", en: "Page" },
  reco_h: { vi: "Gợi ý tài liệu và công trình khác", en: "Suggested alternative sources" },
  reco_d: { vi: "Điểm dưới 60: tài liệu này chỉ liên quan ở mức thấp. Dưới đây là hướng tìm nguồn tốt hơn, các công trình tương tự (OpenAlex) và tạp chí đối chiếu với cơ sở dữ liệu EduFind.", en: "Score below 60: this document is only marginally relevant. Below are directions for better sources, similar works (OpenAlex) and journals matched against the EduFind database." },
  reco_advice: { vi: "Nên tìm gì thay thế", en: "What to look for instead" },
  reco_queries: { vi: "Tìm trên Google Scholar", en: "Search on Google Scholar" },
  reco_works: { vi: "Công trình tương tự", en: "Similar works" },
  reco_journals: { vi: "Tạp chí uy tín gợi ý", en: "Suggested reputable journals" },
  reco_none: { vi: "Chưa tìm thấy kết quả phù hợp.", en: "No suitable results found." },
  from_edufind: { vi: "đối chiếu với EduFind", en: "matched against EduFind" },
  cited_by: { vi: "{n} trích dẫn", en: "{n} citations" },
  journal: { vi: "Tạp chí", en: "Journal" },
  rank: { vi: "Xếp hạng", en: "Rank" },
  note: { vi: "Ghi chú", en: "Note" },
  hdgs_max: { vi: "HĐGSNN tối đa {n} điểm", en: "State Council up to {n} pts" },
  why_venue: { vi: "Nơi đăng các công trình tương tự", en: "Publishes similar works" },
  why_keyword: { vi: "Khớp từ khóa chuyên ngành", en: "Matches subject keywords" },
  open_edufind: { vi: "Mở EduFind để lọc tạp chí", en: "Open EduFind to filter journals" },
  edufind_note: { vi: "cơ sở dữ liệu tạp chí khoa học theo chuẩn Hội đồng Giáo sư nhà nước", en: "journal database aligned with Vietnam's State Professorship Council" },

  // ----- Trích dẫn -----
  cite_style: { vi: "Kiểu trích dẫn", en: "Citation style" },
  cite_lang: { vi: "Ngôn ngữ trích dẫn", en: "Citation language" },
  cl_vi: { vi: "Tiếng Việt (và, tr., và cs.)", en: "Vietnamese (và, tr., và cs.)" },
  cl_en: { vi: "Tiếng Anh (&, pp., et al.)", en: "English (&, pp., et al.)" },
  cl_en_note: { vi: "Dùng khi bạn gửi bài cho tạp chí quốc tế. Nhan đề tiếng Việt sẽ kèm bản dịch tiếng Anh trong ngoặc vuông nếu có.", en: "Use this when submitting to an international journal." },
  source_info: { vi: "Thông tin nguồn tài liệu", en: "Source details" },
  meta_incomplete: { vi: "Một số thông tin thư mục (tác giả, năm, nhan đề) chưa có trong tài liệu. Hãy bổ sung trước khi sao chép.", en: "Some bibliographic details (authors, year, title) were not found in the document. Please complete them before copying." },
  src_type: { vi: "Loại tài liệu", en: "Source type" },
  type_article: { vi: "Bài báo tạp chí", en: "Journal article" },
  type_book: { vi: "Sách", en: "Book" },
  type_chapter: { vi: "Chương sách", en: "Book chapter" },
  type_conference: { vi: "Bài hội thảo", en: "Conference paper" },
  type_thesis: { vi: "Luận văn/Luận án", en: "Thesis" },
  type_report: { vi: "Báo cáo", en: "Report" },
  type_web: { vi: "Trang web", en: "Web page" },
  title: { vi: "Nhan đề", en: "Title" },
  title_en: { vi: "Nhan đề dịch sang tiếng Anh", en: "English translation of the title" },
  authors: { vi: "Tác giả", en: "Authors" },
  family: { vi: "Họ (VD: Nguyễn)", en: "Family name" },
  given: { vi: "Tên đệm và tên (VD: Văn An)", en: "Given names" },
  add_author: { vi: "Thêm tác giả", en: "Add author" },
  author_hint: { vi: "Với tên Việt Nam, nhập họ ở ô thứ nhất và tên đệm cùng tên ở ô thứ hai.", en: "For Vietnamese names, put the family name first and the middle and given names second." },
  year: { vi: "Năm", en: "Year" },
  container: { vi: "Tên tạp chí / sách / hội thảo", en: "Journal / book / conference" },
  volume: { vi: "Tập", en: "Volume" },
  issue: { vi: "Số", en: "Issue" },
  pages: { vi: "Trang", en: "Pages" },
  publisher: { vi: "Nhà xuất bản", en: "Publisher" },
  reference_entry: { vi: "Mục tài liệu tham khảo", en: "Reference entry" },
  reference: { vi: "Tài liệu tham khảo", en: "Reference" },
  in_text: { vi: "Trích dẫn trong văn bản", en: "In-text citation" },
  quote: { vi: "Đoạn trích", en: "Quote" },
  everything: { vi: "Toàn bộ", en: "Everything" },
  numbered_note: { vi: "Kiểu đánh số: số thứ tự phụ thuộc vị trí nguồn trong danh mục của bạn; hãy đổi số cho khớp.", en: "Numbered style: the number depends on this source's position in your list; adjust it to match." },
  quotes_selected: { vi: "{n} đoạn trích đã chọn", en: "{n} selected quote(s)" },
  copy: { vi: "Sao chép", en: "Copy" },
  copy_all: { vi: "Sao chép tất cả", en: "Copy all" },
  copy_quote: { vi: "Sao chép đoạn + trích dẫn", en: "Copy quote + citation" },
  copy_in_text: { vi: "Chỉ trích dẫn", en: "Citation only" },
  copy_link: { vi: "Sao chép liên kết", en: "Copy link" },
  copied: { vi: "Đã sao chép: {what}. Có thể dán vào Word, Zotero hoặc phần mềm khác.", en: "Copied: {what}. You can paste it into Word, Zotero or any other tool." },
  copy_fail: { vi: "Không sao chép được. Hãy bôi đen và sao chép thủ công.", en: "Could not copy. Please select and copy manually." },
  csl_more: { vi: "Kiểu khác: hơn 10.000 tạp chí và trường (CSL)", en: "More styles: 10,000+ journals and universities (CSL)" },
  csl_hint: { vi: "Gõ tên tạp chí hoặc kiểu trích dẫn (ví dụ: Computers & Education, Nature, Chicago, Vancouver). Kiểu của tạp chí lấy theo yêu cầu từ kho CSL.", en: "Type a journal or style name (e.g. Computers & Education, Nature, Chicago, Vancouver). Journal styles are fetched on demand from the CSL repository." },
  csl_search: { vi: "Tìm theo tên tạp chí hoặc kiểu…", en: "Search by journal or style name…" },
  csl_selected: { vi: "Đang dùng", en: "Using" },
  csl_choose: { vi: "Hãy chọn một kiểu CSL ở danh sách trên.", en: "Choose a CSL style from the list above." },
  csl_fail: { vi: "Không tải được kiểu CSL. Hãy kiểm tra kết nối mạng hoặc chọn kiểu khác.", en: "Could not load the CSL style. Check your connection or pick another style." },
  csl_credit: { vi: "Kiểu trích dẫn: dự án Citation Style Language (CC BY-SA 3.0); bộ máy citeproc-js.", en: "Styles: Citation Style Language project (CC BY-SA 3.0); engine: citeproc-js." },
  history_note: { vi: "Mỗi lần sao chép, trích dẫn được lưu vào Lịch sử. Tài liệu tải lên không được lưu.", en: "Each copy is saved to your History. Uploaded documents are not stored." },

  // ----- Lịch sử -----
  hist_title: { vi: "Lịch sử trích dẫn", en: "Citation history" },
  hist_note: { vi: "Chỉ những trích dẫn bạn đã sao chép thành công mới được lưu.", en: "Only citations you have successfully copied are saved." },
  hist_empty: { vi: "Chưa có trích dẫn nào.", en: "No citations yet." },
  search: { vi: "Tìm kiếm…", en: "Search…" },
  all_styles: { vi: "Mọi kiểu", en: "All styles" },
  export: { vi: "Xuất danh mục (.txt)", en: "Export list (.txt)" },

  // ----- Hồ sơ -----
  profile_empty: { vi: "Hãy hoàn thiện hồ sơ nhà nghiên cứu của bạn.", en: "Complete your researcher profile." },
  completeness: { vi: "Mức hoàn thiện hồ sơ", en: "Profile completeness" },
  role_admin: { vi: "Quản trị viên", en: "Administrator" },
  role_user: { vi: "Người dùng", en: "User" },
  sec_identity: { vi: "Danh tính học thuật", en: "Academic identity" },
  sec_affil: { vi: "Đơn vị công tác", en: "Affiliation" },
  sec_research: { vi: "Lĩnh vực nghiên cứu", en: "Research profile" },
  sec_links: { vi: "Liên kết học thuật", en: "Scholarly links" },
  acad_title: { vi: "Học hàm, học vị", en: "Academic title" },
  country: { vi: "Quốc gia", en: "Country" },
  phone: { vi: "Điện thoại", en: "Phone" },
  affiliation: { vi: "Cơ quan, trường, viện", en: "Institution" },
  department: { vi: "Khoa, bộ môn", en: "Department" },
  position: { vi: "Chức vụ", en: "Position" },
  fields: { vi: "Lĩnh vực nghiên cứu", en: "Research fields" },
  fields_ph: { vi: "Gõ rồi nhấn Enter", en: "Type and press Enter" },
  keywords: { vi: "Từ khóa nghiên cứu", en: "Research keywords" },
  keywords_ph: { vi: "Gõ rồi nhấn Enter", en: "Type and press Enter" },
  bio: { vi: "Giới thiệu ngắn", en: "Short biography" },
  website: { vi: "Trang web cá nhân", en: "Personal website" },
  orcid_import: { vi: "Nhập từ ORCID", en: "Import from ORCID" },
  orcid_hint: { vi: "Định dạng 0000-0000-0000-0000. Nút nhập chỉ lấy dữ liệu công khai trên ORCID và không ghi đè ô bạn đã điền.", en: "Format 0000-0000-0000-0000. Import uses only public ORCID data and never overwrites fields you filled in." },
  orcid_bad: { vi: "ORCID iD không hợp lệ (sai định dạng hoặc chữ số kiểm tra).", en: "Invalid ORCID iD (format or check digit)." },
  orcid_imported: { vi: "Đã nhập dữ liệu công khai từ ORCID. Hãy kiểm tra rồi bấm Lưu.", en: "Imported public ORCID data. Review it, then Save." },
  orcid_fail: { vi: "Không lấy được dữ liệu từ ORCID.", en: "Could not fetch data from ORCID." },

  // ----- Quản trị -----
  admin_title: { vi: "Trang quản trị", en: "Administration" },
  adm_users: { vi: "Người dùng", en: "Users" },
  adm_settings: { vi: "Cài đặt", en: "Settings" },
  adm_stats: { vi: "Thống kê", en: "Statistics" },
  adm_search: { vi: "Tìm theo email, tên, ORCID, đơn vị…", en: "Search by email, name, ORCID, institution…" },
  adm_total: { vi: "{n} người dùng", en: "{n} users" },
  adm_user: { vi: "Người dùng", en: "User" },
  adm_today: { vi: "Dùng hôm nay", en: "Used today" },
  adm_bonus: { vi: "Lượt cấp thêm", en: "Granted left" },
  adm_life: { vi: "Tổng đã dùng", en: "Total used" },
  adm_grant: { vi: "Cấp / thu hồi lượt", en: "Grant / revoke" },
  adm_role: { vi: "Quyền & trạng thái", en: "Role & status" },
  adm_suspend: { vi: "Khóa", en: "Suspend" },
  adm_make_admin: { vi: "Nâng lên quản trị", en: "Make admin" },
  adm_revoke_admin: { vi: "Hạ xuống người dùng", en: "Revoke admin" },
  adm_unsuspend: { vi: "Mở khóa", en: "Unsuspend" },
  granted: { vi: "Đã cập nhật {n} lượt cho {email}.", en: "Adjusted {n} credit(s) for {email}." },
  adm_quota_h: { vi: "Hạn mức miễn phí", en: "Free allowance" },
  adm_free_limit: { vi: "Số lượt miễn phí mỗi ngày", en: "Free analyses per day" },
  adm_free_hint: { vi: "Áp dụng cho mọi người dùng thường. Quản trị viên không bị giới hạn. Đặt lại lúc 00:00 giờ Việt Nam.", en: "Applies to all regular users. Admins are unlimited. Resets at 00:00 Vietnam time." },
  adm_contact_h: { vi: "Thông tin liên hệ hiển thị khi người dùng hết lượt", en: "Contact details shown when a user runs out" },
  zalo_ph: { vi: "Số Zalo (nếu khác số điện thoại)", en: "Zalo number (if different from phone)" },
  adm_note_vi: { vi: "Ghi chú (tiếng Việt)", en: "Note (Vietnamese)" },
  adm_note_en: { vi: "Ghi chú (tiếng Anh)", en: "Note (English)" },
  st_users: { vi: "Tổng người dùng", en: "Total users" },
  st_new_7d: { vi: "Đăng ký mới 7 ngày", en: "New in 7 days" },
  st_analyses_today: { vi: "Lượt phân tích hôm nay", en: "Analyses today" },
  st_analyses_7d: { vi: "Lượt phân tích 7 ngày", en: "Analyses, 7 days" },
  st_analyses_total: { vi: "Tổng lượt phân tích", en: "Total analyses" },
  st_citations_total: { vi: "Trích dẫn đã lưu", en: "Citations saved" },
  st_bonus_outstanding: { vi: "Lượt cấp thêm còn lại", en: "Granted credits outstanding" },
  st_exhausted_today: { vi: "Người dùng hết lượt hôm nay", en: "Users out of credits today" },
  visits_countries: { vi: "Quốc gia truy cập nhiều nhất", en: "Top visitor countries" },
  visits_off: { vi: "Bộ đếm truy cập chưa bật (cần cấu hình Upstash Redis, xem README).", en: "Visit counter is off (configure Upstash Redis, see README)." },

  // ----- Chân trang, chia sẻ -----
  foot_about: { vi: "Trợ lý AI giúp đọc tài liệu, tóm tắt thông tin và trích dẫn theo chuẩn khoa học.", en: "An AI assistant that helps you read sources, summarise them and cite to scholarly standards." },
  author: { vi: "Tác giả", en: "Author" },
  author_note: { vi: "Thiết kế và phát triển bởi tác giả; mọi quyền được bảo lưu.", en: "Designed and developed by the author; all rights reserved." },
  visits_head: { vi: "Lượt truy cập", en: "Visits" },
  visits_title: { vi: "Thống kê ẩn danh, không lưu IP", en: "Anonymous statistics, no IP stored" },
  visits_total: { vi: "lượt truy cập", en: "visits" },
  visits_today: { vi: "hôm nay", en: "today" },
  rights: { vi: "Bản quyền đóng. Mọi quyền được bảo lưu.", en: "Proprietary software. All rights reserved." },
  rights_detail: { vi: "Không được sao chép, phân phối lại, dịch ngược hoặc khai thác thương mại phần mềm và giao diện này nếu chưa có văn bản cho phép của tác giả. Dữ liệu và thư viện bên thứ ba thuộc quyền của chủ sở hữu tương ứng.", en: "No copying, redistribution, reverse engineering or commercial exploitation of this software and interface without the author's written permission. Third-party data and libraries remain the property of their respective owners." },
  share: { vi: "Chia sẻ", en: "Share" },
  zalo_copied: { vi: "Đã sao chép liên kết. Hãy dán vào Zalo để chia sẻ.", en: "Link copied. Paste it into Zalo to share." },
  link_copied: { vi: "Đã sao chép liên kết.", en: "Link copied." },
} as const satisfies Record<string, { vi: string; en: string }>;

export type Key = keyof typeof D;
export const DICT: Record<string, { vi: string; en: string }> = D;
